services:
  accounts:
    image: "rvmakawana/accounts:v1"
    container_name: accounts
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700M
    networks:
      - rvbank
  loan:
    image: "rvmakawana/loan:v1"
    container_name: loans
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700M
    networks:
      - rvbank
  card:
    image: "rvmakawana/card:v1"
    container_name: cards
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700M
    networks:
      - rvbank
networks:
  rvbank:
    driver: "bridge"